const PROFIT_MARGIN=0.25;
const BATTERY_PRICES={none:{name:"No Battery / Bring Your Own",price:0},disposable:{name:"Disposable / Heavy-Duty Pack (+₹120)",price:120},rechargeable:{name:"Rechargeable Li-Ion + Charger (+₹380)",price:380}};
const projectData={
car:{title:"ESP8266 2WD Bluetooth RC Car",category:"Embedded Systems",basePrice:950,summary:"2WD chassis with ESP8266 + HC-05 Bluetooth PWM control.",wiring:[{component:"L298N IN1",pin:"D5 (GPIO14)"},{component:"L298N IN2",pin:"D6 (GPIO12)"},{component:"L298N IN3",pin:"D7 (GPIO13)"},{component:"L298N IN4",pin:"D8 (GPIO15)"},{component:"HC-05 RX/TX",pin:"D1 / D2"}],code:"SoftwareSerial BT(D1,D2);\n// F=Forward B=Back L=Left R=Right S=Stop\nvoid forward(){digitalWrite(D5,HIGH);digitalWrite(D6,LOW);digitalWrite(D7,HIGH);digitalWrite(D8,LOW);}"},
joystick:{title:"Arduino Uno PS2 Bluetooth Remote Controller",category:"Control Systems",basePrice:850,summary:"Master transmitter with joysticks + LCD + servo.",wiring:[{component:"Joystick X",pin:"A0"},{component:"Joystick Y",pin:"A1"},{component:"Servo",pin:"D9"},{component:"HC-05",pin:"D2/D3"}],code:"int x=analogRead(A0),y=analogRead(A1);\nif(y>700)BT.write('F');\nelse if(y<300)BT.write('B');\nelse BT.write('S');"},
radar:{title:"Ultrasonic Radar Scanner",category:"Robotics",basePrice:650,summary:"180-degree sweep mapping with HC-SR04.",wiring:[{component:"Trig",pin:"D10"},{component:"Echo",pin:"D11"},{component:"Servo",pin:"D9"}],code:"for(int i=15;i<=165;i++){servo.write(i);Serial.println(getDistance());}"},
plant:{title:"Smart Plant Monitor",category:"IoT",basePrice:550,summary:"Auto pump when soil dry.",wiring:[{component:"Soil Sensor",pin:"A0"},{component:"Relay",pin:"D7"}],code:"if(analogRead(A0)>400)digitalWrite(7,LOW);else digitalWrite(7,HIGH);"},
alarm:{title:"Motion Security Alarm",category:"Security",basePrice:480,summary:"PIR relay alarm.",wiring:[{component:"PIR",pin:"D2"},{component:"Relay",pin:"D4"}],code:"if(digitalRead(2)==HIGH){digitalWrite(4,HIGH);delay(5000);}else digitalWrite(4,LOW);"},
weather:{title:"Micro Weather Station",category:"Embedded",basePrice:590,summary:"Temp + humidity.",wiring:[{component:"DHT11",pin:"D4"}],code:"#include<DHT.h>\nDHT dht(4,DHT11);\nSerial.print(dht.readTemperature());"},
pump:{title:"Water Pump Automation Unit",category:"Automation",basePrice:720,summary:"Prevents dry run.",wiring:[{component:"Water Sensor",pin:"A0"},{component:"Relay",pin:"D8"}],code:"int v=analogRead(A0);\nif(v<200)digitalWrite(8,LOW);\nelse if(v>600)digitalWrite(8,HIGH);"},
lamp:{title:"Automatic Night Lamp",category:"Embedded",basePrice:380,summary:"LDR auto light.",wiring:[{component:"LDR",pin:"A0"},{component:"Relay",pin:"D3"}],code:"if(analogRead(A0)<300)digitalWrite(3,HIGH);else digitalWrite(3,LOW);"}
};
function calculatePrice(b,e=0){const s=b+e,p=Math.round(s*PROFIT_MARGIN);return{subtotal:s,profit:p,total:s+p}}
let storedRequests=JSON.parse(localStorage.getItem("nexus_requests")||"[]");
function escapeHtml(s){return (s||'').replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function showMainPage(){document.getElementById('project-detail-view').style.display='none';document.getElementById('admin-view').style.display='none';document.getElementById('main-view').style.display='block'}
function updateComponentPrice(){const sel=document.getElementById('comp_item');if(!sel)return;const base=parseInt(sel.options[sel.selectedIndex].dataset.price||390);const qty=parseInt(document.getElementById('comp_quantity').value)||1;const tb=base*qty,pr=Math.round(tb*PROFIT_MARGIN),tot=tb+pr;document.getElementById('comp-base-display').innerText='₹'+tb;document.getElementById('comp-profit-display').innerText='₹'+pr;document.getElementById('comp-total-display').innerText='₹'+tot;document.getElementById('comp-btn-display').innerText='₹'+tot}
function openProject(key){const d=projectData[key];if(!d)return;const pr=calculatePrice(d.basePrice,0);const rows=d.wiring.map(w=>`<tr><td><strong>${w.component}</strong></td><td>${w.pin}</td></tr>`).join('');
document.getElementById('detail-content').innerHTML=`<h2>${d.title}</h2><p class="highlight">Division: ${d.category}</p>
<div class="pricing-box"><div class="price-label">Price Details</div><div class="price-main"><span id="display-total-price">₹${pr.total}</span><span class="price-sub">(Incl. 25% margin)</span></div><div class="badge-profit">✔ 25% Engineering Margin</div><div class="delivery-notice">🚚 Delivery: <strong>Announced later</strong></div><div class="base-line">Base ₹${d.basePrice} | Margin <span id="display-profit-price">₹${pr.profit}</span></div></div>
<div class="card"><h3>Overview</h3><p>${d.summary}</p></div>
<div class="card"><h3>Pinouts</h3><table><tr><th>Module</th><th>Pin</th></tr>${rows}</table></div>
<div class="card"><h3>Code</h3><pre><code>${escapeHtml(d.code)}</code></pre></div>
<div class="card"><h3>🛠️ Order This Build</h3>
<form onsubmit="handleFormSubmit(event,'${escapeHtml(d.title)}',${d.basePrice})">
<div class="form-group"><label>Battery:</label><select id="battery_choice" onchange="updateDynamicPrice(${d.basePrice})"><option value="none">No Battery</option><option value="disposable">Disposable Pack (+₹120)</option><option value="rechargeable">Rechargeable Li-Ion + Charger (+₹380)</option></select></div>
<div class="customization-box"><div class="form-group" style="margin:0"><label>✏️ Customization:</label><textarea id="project_customization" placeholder="OLED, buzzer, wires, enclosure..."></textarea></div></div>
<div class="form-group"><label>Name:</label><input id="user_name" required placeholder="Your name"/></div>
<div class="form-group"><label>Email:</label><input id="user_email" type="email" required placeholder="name@example.com"/></div>
<div class="form-group"><label>Phone:</label><input id="user_phone" required placeholder="+91 XXXXXXXXXX"/></div>
<div class="form-group"><label>Address:</label><input id="user_location" required placeholder="City, State, Pincode"/></div>
<div class="form-group"><label>Category:</label><select id="user_category"><option>Personal / Hobbyist</option><option>School / Academic</option><option>Professional</option></select></div>
<div class="form-group"><label>School/Company:</label><input id="user_org" required placeholder="Organization"/></div>
<button class="submit-btn" type="submit">🚀 Save Order (<span id="btn-price-display">₹${pr.total}</span>)</button>
<button class="whatsapp-btn" type="button" onclick="orderProjectWhatsApp('${escapeHtml(d.title)}')">💬 Order on WhatsApp</button>
</form><div id="intake-summary" class="summary-box"></div></div>`;
document.getElementById('main-view').style.display='none';document.getElementById('admin-view').style.display='none';document.getElementById('project-detail-view').style.display='block';window.scrollTo({top:0,behavior:'smooth'})}
function updateDynamicPrice(b){const k=document.getElementById('battery_choice').value;const ex=BATTERY_PRICES[k]?BATTERY_PRICES[k].price:0;const p=calculatePrice(b,ex);document.getElementById('display-total-price').innerText='₹'+p.total;document.getElementById('display-profit-price').innerText='₹'+p.profit;document.getElementById('btn-price-display').innerText='₹'+p.total}
function orderProjectWhatsApp(t){const b=document.getElementById('battery_choice');const bt=b?b.options[b.selectedIndex].text:"Std";const c=document.getElementById('project_customization')?.value||"None";const pr=document.getElementById('display-total-price')?.innerText||"";window.open(`https://wa.me/918281349340?text=${encodeURIComponent(`Hi Adnan! I want "${t}"\n- Battery: ${bt}\n- Custom: ${c}\n- Price: ${pr}`)}`,'_blank')}
function orderComponentWhatsApp(){const s=document.getElementById('comp_item');const msg=`Hi Adnan! Component Order:\n- Item: ${s.value}\n- Qty: ${document.getElementById('comp_quantity').value}\n- Specs: ${document.getElementById('comp_customization').value||"None"}\n- Total: ${document.getElementById('comp-total-display').innerText}`;window.open('https://wa.me/918281349340?text='+encodeURIComponent(msg),'_blank')}
function orderCustomDevWhatsApp(){window.open('https://wa.me/918281349340?text='+encodeURIComponent(`Hi Adnan! Custom project:\n- Service: ${document.getElementById('custom_type').value}\n- Details: ${document.getElementById('custom_details').value||"Discuss"}`),'_blank')}
function handleFormSubmit(e,title,base){e.preventDefault();const bk=document.getElementById('battery_choice').value;const bi=BATTERY_PRICES[bk];const fp=calculatePrice(base,bi.price);const rec={id:Date.now(),request_type:"Hardware Build",project_name:title,user_name:val('user_name'),user_email:val('user_email'),user_phone:val('user_phone'),user_location:val('user_location'),user_category:val('user_category'),user_org:val('user_org'),battery:bi.name,customization:val('project_customization')||"Standard",calculated_price:`₹${fp.total} (Base ₹${base}+Batt ₹${bi.price}+25% ₹${fp.profit})`,delivery_note:"Later by address",time:new Date().toLocaleString()};saveRec(rec);showBox('intake-summary',`ORDER CONFIRMED<br>Maker: ${escapeHtml(rec.user_name)}<br>Project: ${title}<br>Battery: ${bi.name}<br><b style="color:var(--gold);font-size:1.2rem">Total ₹${fp.total}</b><br>Status: LOGGED`)}
function handleComponentSubmit(e){e.preventDefault();const s=document.getElementById('comp_item');const bu=parseInt(s.options[s.selectedIndex].dataset.price);const q=parseInt(val('comp_quantity'))||1;const tb=bu*q,pr=Math.round(tb*PROFIT_MARGIN),tot=tb+pr;const rec={id:Date.now(),request_type:"Component Order",project_name:`${s.value} (x${q})`,user_name:val('comp_user_name'),user_email:val('comp_user_email'),user_phone:val('comp_user_phone'),user_location:val('comp_user_address'),user_category:"Component",user_org:"Individual",battery:"N/A",customization:val('comp_customization')||"Standard",calculated_price:`₹${tot} (Base ₹${tb}+25% ₹${pr})`,delivery_note:"Later",time:new Date().toLocaleString()};saveRec(rec);showBox('comp-summary',`COMPONENT ORDER CONFIRMED<br>${escapeHtml(rec.project_name)}<br><b style="color:var(--gold);font-size:1.2rem">Total ₹${tot}</b>`)}
function handleCustomSubmit(e){e.preventDefault();const rec={id:Date.now(),request_type:"Custom Software",project_name:val('custom_type'),user_name:val('custom_name'),user_email:val('custom_email'),user_phone:val('custom_phone'),user_location:"N/A",user_category:"Custom",user_org:val('custom_org'),battery:"N/A",customization:val('custom_details'),calculated_price:"Custom Quote +25%",delivery_note:"Digital",time:new Date().toLocaleString()};saveRec(rec);showBox('custom-summary',`CUSTOM ORDER RECEIVED<br>Client: ${escapeHtml(rec.user_name)}<br>Service: ${escapeHtml(rec.project_name)}`);document.getElementById('custom-dev-form').reset()}
// FREE-WRITE BOX
function updateFreeformPreview(){const t=document.getElementById('free_items').value;document.getElementById('free-live-count').innerText=t.length+" characters";document.getElementById('free-preview-box').innerText=t?("✨ Draft Order:\n"+t+`\n\nBudget: ${document.getElementById('free_budget').value} | ${document.getElementById('free_urgency').value}`):"✨ Live Preview: Start typing above..."}
function handleFreeformSubmit(e){e.preventDefault();const rec={id:Date.now(),request_type:"Free-Write Box Order",project_name:`Custom Free Order [${val('free_budget')}]`,user_name:val('free_name'),user_email:"via-free-box",user_phone:val('free_phone'),user_location:val('free_address'),user_category:val('free_urgency'),user_org:val('free_budget'),battery:"N/A",customization:val('free_items'),calculated_price:"AI Quote Pending +25% margin",delivery_note:"Later",time:new Date().toLocaleString()};saveRec(rec);showBox('free-summary',`FREE-WRITE ORDER SAVED ✅<br>Name: ${escapeHtml(rec.user_name)}<br>Need: ${escapeHtml(rec.customization).substring(0,200)}<br>Status: LOGGED - Adnan will reply with price`)}
function orderFreeformWhatsApp(){const msg=`Hi Adnan! Custom Free Order:\n- Need: ${document.getElementById('free_items').value}\n- Budget: ${document.getElementById('free_budget').value}\n- Urgency: ${document.getElementById('free_urgency').value}\n- Name: ${document.getElementById('free_name').value}`;window.open('https://wa.me/918281349340?text='+encodeURIComponent(msg),'_blank')}
function val(id){return document.getElementById(id)?.value||""}
function saveRec(r){storedRequests.unshift(r);localStorage.setItem("nexus_requests",JSON.stringify(storedRequests))}
function showBox(id,html){const b=document.getElementById(id);b.innerHTML=html;b.style.display='block';b.scrollIntoView({behavior:'smooth',block:'nearest'})}
function accessSubmissions(){if(prompt("Enter Admin Password:")!=="nexus@sub"){alert("Access Denied");return}document.getElementById('main-view').style.display='none';document.getElementById('project-detail-view').style.display='none';document.getElementById('admin-view').style.display='block';window.scrollTo({top:0,behavior:'smooth'});fetchSubmissions()}
function dismissRequest(id){storedRequests=storedRequests.filter(s=>s.id!==id);localStorage.setItem("nexus_requests",JSON.stringify(storedRequests));fetchSubmissions()}
function fetchSubmissions(){const c=document.getElementById('submissions-list');if(!storedRequests.length){c.innerHTML='<p style="color:#34d399">No submissions.</p>';return}c.innerHTML=storedRequests.map((s,i)=>`<div class="sub-card"><h4 style="color:var(--cyan)">#${storedRequests.length-i} [${escapeHtml(s.request_type)}] ${escapeHtml(s.project_name)}</h4><p>Time: ${escapeHtml(s.time)}</p><p>Name: ${escapeHtml(s.user_name)} | Phone: ${escapeHtml(s.user_phone)}</p><p>Custom: <span style="color:var(--gold)">${escapeHtml(s.customization||"None")}</span></p><p>Price: <b style="color:#34d399">${escapeHtml(s.calculated_price)}</b></p><p>Loc: ${escapeHtml(s.user_location)} | Org: ${escapeHtml(s.user_org)}</p><button class="ok-btn" onclick="dismissRequest(${s.id})">OK</button></div>`).join('')}
// AI ANIMATIONS
window.addEventListener('load',()=>{setTimeout(()=>document.getElementById('preloader').classList.add('hide'),900);updateComponentPrice();initReveal();initTyping();initCanvas();});
window.addEventListener('scroll',()=>{const h=document.documentElement;const p=(h.scrollTop/(h.scrollHeight-h.clientHeight))*100;document.getElementById('scroll-progress').style.width=p+'%'});
document.addEventListener('mousemove',e=>{const g=document.getElementById('cursor-glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});
function initReveal(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>o.observe(el));
document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(800px) rotateY(${x*10}deg) rotateX(${-y*10}deg) translateY(-5px)`});card.addEventListener('mouseleave',()=>card.style.transform='')})}
function initTyping(){const phrases=["Future Robotics & AI Research Organization","Arduino • ESP32 • Python • Kotlin • AI","Custom Builds • Science Fair • Components"];let pi=0,ci=0,del=false;const el=document.getElementById('typing-text');(function tick(){const cur=phrases[pi];el.textContent=cur.slice(0,ci);if(!del){ci++;if(ci>cur.length){del=true;setTimeout(tick,1400);return}}else{ci--;if(ci===0){del=false;pi=(pi+1)%phrases.length}}setTimeout(tick,del?35:65)})()}
function initCanvas(){const c=document.getElementById('ai-canvas');if(!c)return;const ctx=c.getContext('2d');let W,H,pts=[];function resize(){W=c.width=c.offsetWidth;H=c.height=c.offsetHeight}resize();window.addEventListener('resize',resize);for(let i=0;i<70;i++)pts.push({x:Math.random()*2000,y:Math.random()*1000,vx:(Math.random()-.5)*.6,vy:(Math.random()-.5)*.6});(function anim(){ctx.clearRect(0,0,W,H);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>W)p.vx*=-1;if(p.y<0||p.y>H)p.vy*=-1;ctx.beginPath();ctx.arc(p.x%W,p.y%H,1.8,0,7);ctx.fillStyle='#00f5ff';ctx.fill()});for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j];const dx=(a.x%W)-(b.x%W),dy=(a.y%H)-(b.y%H);const d=Math.hypot(dx,dy);if(d<120){ctx.strokeStyle=`rgba(0,245,255,${(1-d/120)*.35})`;ctx.beginPath();ctx.moveTo(a.x%W,a.y%H);ctx.lineTo(b.x%W,b.y%H);ctx.stroke()}}requestAnimationFrame(anim)})()}
function toggleAiHelper(){document.getElementById('ai-modal').classList.toggle('open')}
function sendAiMessage(){const inp=document.getElementById('ai-input');const t=inp.value.trim();if(!t)return;const box=document.getElementById('ai-chat-box');box.innerHTML+=`<div class="user-msg">${escapeHtml(t)}</div>`;inp.value='';let r="Great! For exact quote, use the Write Anything box or WhatsApp +91 8281349340. Adnan replies fast!";const l=t.toLowerCase();if(l.includes('price')||l.includes('cost'))r="All builds include 25% margin. Example: RC Car ₹1188, Radar ₹813, Night Lamp ₹475. Delivery extra by address.";else if(l.includes('arduino'))r="Yes! We have Uno R3 (₹488 with margin), Nano, ESP8266, ESP32. Use Components Store or write freely in AI Box.";else if(l.includes('deliver'))r="We deliver across India. Fee announced by pincode. Normal 5-7 days, urgent 2-3 days possible.";else if(l.includes('science')||l.includes('fair')||l.includes('school'))r="For fairs: Blind Stick ₹750, Dustbin ₹690, Anti-sleep ₹820, Home Automation ₹950. All ready-to-demo with chart!";else if(l.includes('hi')||l.includes('hello'))r="Hello! 👋 Want a robot, sensor, or fair project? Tell me your budget and I’ll suggest.";setTimeout(()=>{box.innerHTML+=`<div class="ai-msg">${r}</div>`;box.scrollTop=box.scrollHeight},500)}